steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'asia-southeast2-docker.pkg.dev/bangkit-2023-386023/go-sample-repository/goimage:$SHORT_SHA', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'asia-southeast2-docker.pkg.dev/bangkit-2023-386023/go-sample-repository/goimage:$SHORT_SHA']

  # Set zone
  - name: gcr.io/cloud-builders/gcloud
    args: [ 'config', 'set', 'compute/zone', 'asia-southeast2-a']

  # Entrypoint, timeout and environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    timeout: 240s
    args: ['compute', 'instances', 
           'update-container', 'go-vm-sample',
           '--container-image', 
           'asia-southeast2-docker.pkg.dev/bangkit-2023-386023/go-sample-repository/goimage:$SHORT_SHA']

# Save test logs to Google Cloud Storage
artifacts:
  objects:
    location: gs://go-sample-bucket/
    paths:
      - ${SHORT_SHA}_test_log.xml

# Store images in Google Artifact Registry
images:
  - asia-southeast2-docker.pkg.dev/bangkit-2023-386023/go-sample-repository/goimage:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY